### ISSUE TITLE
【スクール】学習報告の学習名が謎の表示「aiuea」になる。

### ISSUE THREAD

**Issue by endoTakashi** [endoTakashi/leranpot2#19]

**Comment by kt0319** [comment]
学習項目でもそのようなデータはないということですよね？
こちらもスクリーンショットを貼れますか？

**Comment by endoTakashi** [comment]
<img width="801" alt="スクリーンショット 2019-04-05 23 04 07" src="https://user-images.githubusercontent.com/16441533/55633373-3046dd80-57f7-11e9-8617-3e91ad06bff5.png">

**Comment by endoTakashi** [comment]
詳細に行った時にこうなります！

**Comment by kt0319** [comment]
修正ずみ
